### ISSUE TITLE
Indexing Errors

### ISSUE THREAD

**Issue by samueljsluo** [allenyummy/KeyExtractor#12]
您好，請問我在抽取關鍵詞時出現了這樣的警告
Token indices sequence length is longer than the specified maximum sequence length for this model (5299269 > 512). Running this sequence through the model will result in indexing errors
請問indexing errors會有什麼後果嗎？謝謝

**Comment by allenyummy** [comment]
因為我使用的是 transformers-based 的模型來作為詞向量抽取器，大部分的 transformers-based 模型皆有設置最大長度限制 512 tokens，當超過 512 tokens 時，大部分模型的處理方式是 truncate 掉後面的 token，只取前面的 512 tokens 作為輸入 (事實上還要扣除 [CLS] 和 [SEP] 這兩個特殊 token，不過為了方便討論，先忽略此沒有關係)。

回到正題，也就是當 KeyExtractor 輸入的文本長度超過 512 tokens，之後的 token 不可能輸出成關鍵詞。
改進的方式有三：

1.  自行切割過長的輸入，分別餵給 KeyExtractor，讓 KeyExtractor 針對每個部分輸出關鍵詞。但這樣的方式在合併關鍵詞時，須小心斟酌，因為不同部分的關鍵詞分數並無法互相比較。

2.  sliding windows，利用滑窗的方式處理輸入，但這實作上稍麻煩一些。

3. 從文本的視角來看，關鍵詞落在文本前面段落的可能性較大，這也是為何大部分模型會採用前面 512 tokens，也就是說，放心讓 KeyExtractor truncate 後面的 token 吧！

至於 indexing errors 只是警告，可以忽略沒關係，不過後續若有地方出錯，可以再討論！

**Comment by samueljsluo** [comment]
了解了，謝謝您這麼詳細的回答：）
